logs:
  - name: root
    level: info
    appenders:
      - type: FileLogAppender
        file: /logs/ChatRoom/root.log
      - type: StdoutLogAppender
  - name: system
    level: info
    appenders:
      - type: FileLogAppender
        file: /logs/ChatRoom/system.log
      - type: StdoutLogAppender